### ISSUE TITLE
Client need to support both http and https

### ISSUE THREAD

**Issue by chinglinwen** [InsZVA/goout#1]
Visit http site is okay, but https is not

Say I access https://github.com ( many site is using https )
It causes the following error ( at the server side )

2016/05/25 11:05:34 http: panic serving 222.128.5.208:45843: unsupported protocol scheme "collector.githubapp.com"
goroutine 30 [running]:
net/http.(conn).serve.func1(0xc820416b00)
/home/user/soft/go/src/net/http/server.go:1389 +0xc1
panic(0x705300, 0xc8200f3940)
/home/user/soft/go/src/runtime/panic.go:426 +0x4e9
_/home/user/soft/goout/common.(Server).ServeHTTP(0xc82000aeb8, 0x7efc402a7dd0, 0xc8201da750, 0xc82025dce0)
/home/user/soft/goout/common/server.go:23 +0x172
net/http.serverHandler.ServeHTTP(0xc820054080, 0x7efc402a7dd0, 0xc8201da750, 0xc82025dce0)
/home/user/soft/go/src/net/http/server.go:2081 +0x19e
net/http.(conn).serve(0xc820416b00)
/home/user/soft/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(Server).Serve
/home/user/soft/go/src/net/http/server.go:2137 +0x44e
2016/05/25 11:05:34 http: panic serving 222.128.5.208:45834: unsupported protocol scheme "avatars2.githubusercontent.com"
goroutine 32 [running]:
net/http.(conn).serve.func1(0xc820132100)
/home/user/soft/go/src/net/http/server.go:1389 +0xc1
panic(0x705300, 0xc8200f3c80)
/home/user/soft/go/src/runtime/panic.go:426 +0x4e9
_/home/user/soft/goout/common.(Server).ServeHTTP(0xc82000aeb8, 0x7efc402a7dd0, 0xc8201da9c0, 0xc82025ddc0)
/home/user/soft/goout/common/server.go:23 +0x172
net/http.serverHandler.ServeHTTP(0xc820054080, 0x7efc402a7dd0, 0xc8201da9c0, 0xc82025ddc0)
/home/user/soft/go/src/net/http/server.go:2081 +0x19e
net/http.(conn).serve(0xc820132100)
/home/user/soft/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(Server).Serve
/home/user/soft/go/src/net/http/server.go:2137 +0x44e
2016/05/25 11:05:34 http: panic serving 222.128.5.208:45838: unsupported protocol scheme "avatars0.githubusercontent.com"
goroutine 33 [running]:

**Comment by InsZVA** [comment]
Thank you for opening this issue and attention on this project! I am trying to fix it and maybe commit and reply you later.

**Comment by InsZVA** [comment]
It occurs to me that the description of this project is "Go HTTP Proxy", so the https support will not be added to this project, but I maybe create another repo to support socks5 proxy(it will support https, too) in future.

**Comment by chinglinwen** [comment]
Thank you for your reply,  got it now

By the way,  I found another repo can do similar work( https://github.com/cyfdecyf/cow )
You may have interest to take a look

**Comment by InsZVA** [comment]
Yes, it's really a powerful proxy poject, thank you~
